
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"D:\Documentos\Estudos\ASCII\FrontJUS\Tkinter-Designer-master\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1440x1024")
window.configure(bg = "#EFEFEF")


canvas = Canvas(
    window,
    bg = "#EFEFEF",
    height = 1024,
    width = 1440,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    1440.0,
    104.0,
    fill="#6EC1E4",
    outline="")

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    107.0,
    52.0,
    image=image_image_1
)

canvas.create_text(
    205.0,
    18.0,
    anchor="nw",
    text="Checagem de Dados:",
    fill="#FFFFFF",
    font=("JostRoman Regular", 48 * -1)
)

canvas.create_text(
    1068.0,
    42.0,
    anchor="nw",
    text="Gustavo Janot",
    fill="#FFFFFF",
    font=("Calibri", 28 * -1)
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    1357.0,
    52.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    720.0,
    594.0,
    image=image_image_3
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    897.5,
    770.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#EFEFEF",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=618.0,
    y=750.0,
    width=559.0,
    height=43.0
)

canvas.create_text(
    626.0,
    707.0,
    anchor="nw",
    text="Endereço de Residência ou Comercial",
    fill="#000000",
    font=("JostRoman Regular", 24 * -1)
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    411.0,
    770.5,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#EFEFEF",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=238.0,
    y=750.0,
    width=346.0,
    height=43.0
)

canvas.create_text(
    242.0,
    707.0,
    anchor="nw",
    text="Profissão",
    fill="#000000",
    font=("JostRoman Regular", 24 * -1)
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    378.0,
    657.0,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#EFEFEF",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=234.0,
    y=636.0,
    width=288.0,
    height=42.0
)

canvas.create_text(
    242.0,
    586.0,
    anchor="nw",
    text="Nacionalidade",
    fill="#000000",
    font=("JostRoman Regular", 24 * -1)
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    1045.0,
    657.0,
    image=entry_image_4
)
entry_4 = Entry(
    bd=0,
    bg="#EFEFEF",
    fg="#000716",
    highlightthickness=0
)
entry_4.place(
    x=913.0,
    y=636.0,
    width=264.0,
    height=42.0
)

canvas.create_text(
    917.0,
    586.0,
    anchor="nw",
    text="CPF ou CNPJ",
    fill="#000000",
    font=("JostRoman Regular", 24 * -1)
)

entry_image_5 = PhotoImage(
    file=relative_to_assets("entry_5.png"))
entry_bg_5 = canvas.create_image(
    724.0,
    657.0,
    image=entry_image_5
)
entry_5 = Entry(
    bd=0,
    bg="#EFEFEF",
    fg="#000716",
    highlightthickness=0
)
entry_5.place(
    x=579.0,
    y=636.0,
    width=288.0,
    height=42.0
)

canvas.create_text(
    584.0,
    586.0,
    anchor="nw",
    text="Estado Civil",
    fill="#000000",
    font=("JostRoman Regular", 24 * -1)
)

entry_image_6 = PhotoImage(
    file=relative_to_assets("entry_6.png"))
entry_bg_6 = canvas.create_image(
    707.5,
    532.5,
    image=entry_image_6
)
entry_6 = Entry(
    bd=0,
    bg="#EFEFEF",
    fg="#000716",
    highlightthickness=0
)
entry_6.place(
    x=238.0,
    y=509.0,
    width=939.0,
    height=49.0
)

canvas.create_text(
    242.0,
    455.0,
    anchor="nw",
    text="Nome Completo",
    fill="#000000",
    font=("JostRoman Regular", 24 * -1)
)

canvas.create_text(
    233.0,
    341.0,
    anchor="nw",
    text=" Informações da Contratada :",
    fill="#000000",
    font=("JostRoman Regular", 48 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=979.0,
    y=914.0,
    width=270.0,
    height=80.0
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    723.0,
    219.0,
    image=image_image_4
)
window.resizable(False, False)
window.mainloop()
