
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"D:\Documentos\Estudos\ASCII\FrontJUS\Tkinter-Designer-master\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1440x1024")
window.configure(bg = "#EFEFEF")


canvas = Canvas(
    window,
    bg = "#EFEFEF",
    height = 1024,
    width = 1440,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    1440.0,
    104.0,
    fill="#6EC1E4",
    outline="")

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    107.0,
    52.0,
    image=image_image_1
)

canvas.create_text(
    205.0,
    18.0,
    anchor="nw",
    text="Checagem de Dados:",
    fill="#FFFFFF",
    font=("JostRoman Regular", 48 * -1)
)

canvas.create_text(
    1068.0,
    42.0,
    anchor="nw",
    text="Gustavo Janot",
    fill="#FFFFFF",
    font=("Calibri", 28 * -1)
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    1357.0,
    52.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    709.0,
    582.0,
    image=image_image_3
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    886.5,
    698.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#EFEFEF",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=607.0,
    y=678.0,
    width=559.0,
    height=43.0
)

canvas.create_text(
    615.0,
    635.0,
    anchor="nw",
    text="CFOP Principais Produtos",
    fill="#000000",
    font=("JostRoman Regular", 24 * -1)
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    400.0,
    698.5,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#EFEFEF",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=227.0,
    y=678.0,
    width=346.0,
    height=43.0
)

canvas.create_text(
    231.0,
    635.0,
    anchor="nw",
    text="Indústria /  Setor",
    fill="#000000",
    font=("JostRoman Regular", 24 * -1)
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    400.0,
    827.5,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#EFEFEF",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=227.0,
    y=807.0,
    width=346.0,
    height=43.0
)

canvas.create_text(
    231.0,
    764.0,
    anchor="nw",
    text="Receita Anual",
    fill="#000000",
    font=("JostRoman Regular", 24 * -1)
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    371.0,
    585.0,
    image=entry_image_4
)
entry_4 = Entry(
    bd=0,
    bg="#EFEFEF",
    fg="#000716",
    highlightthickness=0
)
entry_4.place(
    x=227.0,
    y=564.0,
    width=288.0,
    height=42.0
)

canvas.create_text(
    231.0,
    514.0,
    anchor="nw",
    text="CNPJ",
    fill="#000000",
    font=("JostRoman Regular", 24 * -1)
)

entry_image_5 = PhotoImage(
    file=relative_to_assets("entry_5.png"))
entry_bg_5 = canvas.create_image(
    1034.0,
    585.0,
    image=entry_image_5
)
entry_5 = Entry(
    bd=0,
    bg="#EFEFEF",
    fg="#000716",
    highlightthickness=0
)
entry_5.place(
    x=902.0,
    y=564.0,
    width=264.0,
    height=42.0
)

canvas.create_text(
    906.0,
    514.0,
    anchor="nw",
    text="CNAE Secundário",
    fill="#000000",
    font=("JostRoman Regular", 24 * -1)
)

entry_image_6 = PhotoImage(
    file=relative_to_assets("entry_6.png"))
entry_bg_6 = canvas.create_image(
    713.0,
    585.0,
    image=entry_image_6
)
entry_6 = Entry(
    bd=0,
    bg="#EFEFEF",
    fg="#000716",
    highlightthickness=0
)
entry_6.place(
    x=569.0,
    y=564.0,
    width=288.0,
    height=42.0
)

canvas.create_text(
    573.0,
    514.0,
    anchor="nw",
    text="CNAE Principal",
    fill="#000000",
    font=("JostRoman Regular", 24 * -1)
)

entry_image_7 = PhotoImage(
    file=relative_to_assets("entry_7.png"))
entry_bg_7 = canvas.create_image(
    696.5,
    465.5,
    image=entry_image_7
)
entry_7 = Entry(
    bd=0,
    bg="#EFEFEF",
    fg="#000716",
    highlightthickness=0
)
entry_7.place(
    x=227.0,
    y=442.0,
    width=939.0,
    height=49.0
)

canvas.create_text(
    231.0,
    383.0,
    anchor="nw",
    text="Nome da sua Empresa",
    fill="#000000",
    font=("JostRoman Regular", 24 * -1)
)

canvas.create_text(
    222.0,
    269.0,
    anchor="nw",
    text=" Informações Empresariais :",
    fill="#000000",
    font=("JostRoman Regular", 48 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=968.0,
    y=932.0,
    width=270.0,
    height=80.0
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    733.0,
    167.0,
    image=image_image_4
)
window.resizable(False, False)
window.mainloop()
