
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"D:\Documentos\Estudos\ASCII\FrontJUS\Tkinter-Designer-master\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1440x1024")
window.configure(bg = "#EFEFEF")


canvas = Canvas(
    window,
    bg = "#EFEFEF",
    height = 1024,
    width = 1440,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    1440.0,
    104.0,
    fill="#6EC1E4",
    outline="")

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    107.0,
    52.0,
    image=image_image_1
)

canvas.create_text(
    205.0,
    18.0,
    anchor="nw",
    text="Checagem de Dados:",
    fill="#FFFFFF",
    font=("JostRoman Regular", 48 * -1)
)

canvas.create_text(
    1068.0,
    42.0,
    anchor="nw",
    text="Gustavo Janot",
    fill="#FFFFFF",
    font=("Calibri", 28 * -1)
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    1357.0,
    52.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    705.0,
    566.0,
    image=image_image_3
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    884.5,
    559.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#EFEFEF",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=593.0,
    y=539.0,
    width=583.0,
    height=43.0
)

canvas.create_text(
    601.0,
    496.0,
    anchor="nw",
    text="Forma de Pagamento",
    fill="#000000",
    font=("JostRoman Regular", 24 * -1)
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    410.0,
    673.5,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#EFEFEF",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=237.0,
    y=653.0,
    width=346.0,
    height=43.0
)

canvas.create_text(
    241.0,
    610.0,
    anchor="nw",
    text="Multa e Encargos",
    fill="#000000",
    font=("JostRoman Regular", 24 * -1)
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    920.5,
    673.5,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#EFEFEF",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=651.0,
    y=653.0,
    width=539.0,
    height=43.0
)

canvas.create_text(
    646.0,
    610.0,
    anchor="nw",
    text="Prazo de Duração",
    fill="#000000",
    font=("JostRoman Regular", 24 * -1)
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    381.0,
    560.0,
    image=entry_image_4
)
entry_4 = Entry(
    bd=0,
    bg="#EFEFEF",
    fg="#000716",
    highlightthickness=0
)
entry_4.place(
    x=237.0,
    y=540.0,
    width=288.0,
    height=42.0
)

canvas.create_text(
    241.0,
    496.0,
    anchor="nw",
    text="Valor",
    fill="#000000",
    font=("JostRoman Regular", 24 * -1)
)

canvas.create_text(
    180.0,
    351.0,
    anchor="nw",
    text=" Informações sobre o Negócio:",
    fill="#000000",
    font=("Consolas", 48 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=978.0,
    y=858.0,
    width=270.0,
    height=80.0
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    700.0,
    212.0,
    image=image_image_4
)
window.resizable(False, False)
window.mainloop()
